name: Build and deploy to VIP Go built branch

on:
  push:
    branches:
      - preprod
      - develop

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Build and deploy to VIP Go built branch
    env:
      DEPLOY_REPO: wpcomvip/wikimediafoundation-org
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Lock PHP and composer versions
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"

      - name: Install Composer Dependencies
        uses: "ramsey/composer-install@v1"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('themes/shiro/package-lock.json', 'plugins/hm-gutenberg-tools/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: (npm --prefix themes/shiro ci && npm --prefix plugins/hm-gutenberg-tools ci && npm --prefix plugins/wikipedia-preview ci)

      - name: Build assets
        run: (npm --prefix themes/shiro run build && npm --prefix plugins/wikipedia-preview run build)

      - name: Run VIP Go Deploy script built
        run: bash .github/vip-go-deploy.sh
        env:
          SRC_REPO: ${{ github.repository }}
          SRC_DIR: ${{ github.workspace }}
          TMP_DIR: ${{ runner.temp }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
