name: Deploy to VIP Go base branch

on:
  push:
    branches:
      - preprod
      - develop

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to VIP Go base branch
    env:
      DEPLOY_REPO: wpcomvip/wikimediafoundation-org
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Push to VIP Go unbuilt
        run: git push "https://git:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ env.DEPLOY_REPO }}.git"
