name: Build and deploy to VIP Go built branch

on:
  push:
    branches:
      - develop
      - preprod

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Build and deploy to VIP Go built branch
    env:
      DEPLOY_REPO: wpcomvip/wikimediafoundation-org
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Lock PHP and composer versions
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"

      - name: Install Composer Dependencies
        uses: "ramsey/composer-install@v2"

      - name: Run VIP Go Deploy script built
        run: bash .github/vip-go-deploy.sh
        env:
          SRC_REPO: ${{ github.repository }}
          SRC_DIR: ${{ github.workspace }}
          TMP_DIR: ${{ runner.temp }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
